## Sample_Numpy_01
 - np.zeros
 - np.array
 - mean,max,min,median,sum
 - np.sort, 逆配列
 - np.count_nonzero
 - np.any
 - np.all
 - np.where
 - np.delete

In [ ]:
# import
import numpy as np

In [ ]:
# 初期化
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# list -> ndarray
a = [10, 20, 30, 40, 40, 50, 20, 50, 20, 30]
b = np.array(a)
a

[10, 20, 30, 40, 40, 50, 20, 50, 20, 30]

In [ ]:
# mean,max,min,median
print(f"平均：{np.mean(a)}")
print(f"最大値：{np.max(a)}")
print(f"最小値：{np.min(a)}")
print(f"中央値：{np.median(a)}")
print(f"合計値：{np.sum(a)}")

平均：5.5
最大値：11
最小値：0
中央値：5.5
合計値：66


In [ ]:
a = np.arange(10,51)
print(a)
print(np.sort(a))
print(a[::-1])
print(np.arange(50, 9, -1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
a = np.arange(0, 12).reshape(3, 4)
print(np.count_nonzero(a < 4))
print(np.count_nonzero(a < 4, axis=0))
print(np.count_nonzero(a < 4, axis=1))

4
[1 1 1 1]
[4 0 0]


In [ ]:
print(np.any(a < 4))
print(np.any(a > 100))
print(np.any(a < 4, axis=0))
print(np.any(a > 100, axis=1))

True
False
[ True  True  True  True]
[False False False]


In [ ]:
print(np.all(a < 4))
print(np.all(a < 100))
print(np.all(a < 4, axis=1))
print(np.all(a < 100, axis=0))

False
True
[ True False False]
[ True  True  True  True]


In [ ]:
print(np.where(a < 5, 44, 99))
print(np.where(a < 5, 44, a))

[[44 44 44 44]
 [44 99 99 99]
 [99 99 99 99]]
[[44 44 44 44]
 [44  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a)
a_del = np.delete(a, 1, axis=0)
print(a_del)
a_del = np.delete(a_del, 2, axis=1)
print(a_del) 
a_del = np.delete(a, 2, axis=None)
print(a_del)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  1  3]
 [ 8  9 11]]
[ 0  1  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a)
print(np.delete(a, [1, 3], axis=1))
print(np.delete(a, [0, 2], axis=0).reshape(4,))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[4 5 6 7]
