## NumPy

In [1]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

### NumPy Arrays (ndarray)

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

In [9]:
type(matrix[0][0])

numpy.int64

In [12]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned +- integer 8bit

In [13]:
ndarray

array([1, 2, 3], dtype=uint8)

In [16]:
ndarray = np.array([1, 2, 3], dtype=np.float64)

In [18]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

### ndarrayの演算

In [19]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

In [20]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Broadcasting

In [29]:
array1 = np.array([1, 2, 3]) 
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

In [30]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [26]:
array2 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Shape

In [33]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
ndarray.shape

(3, 2)

In [37]:
ndarray = ndarray.reshape(2, 3)

In [38]:
ndarray

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [39]:
ndarray = np.random.randn(3, 4, 5, 6, 7)
ndarray.shape

(3, 4, 5, 6, 7)

In [41]:
expand_ndarray = np.expand_dims(ndarray, axis=2)
expand_ndarray.shape

(3, 4, 1, 5, 6, 7)

In [44]:
expand_ndarray = np.squeeze(expand_ndarray)
expand_ndarray.shape

(3, 4, 5, 6, 7)

In [32]:
ndarray1.shape

(3,)

In [33]:
ndarray2.shape

(1, 3)

In [36]:
expand_ndarray = np.expand_dims(ndarray1, axis=-1)

In [37]:
expand_ndarray.shape

(3, 1)

In [59]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [61]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [62]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### IndexingとSlicing

In [63]:
ndarray = np.array([1, 2, 3, 4])

In [64]:
ndarray

array([1, 2, 3, 4])

In [66]:
ndarray[-1]

4

In [67]:
ndarray = np.array([[1, 2],[3, 4],[5, 6]])
ndarray.shape

(3, 2)

In [71]:
ndarray[0, 1]

2

In [72]:
ndarray = np.array([1, 2, 3, 4])

In [73]:
ndarray[1:3]

array([2, 3])

In [74]:
ndarray[:3]

array([1, 2, 3])

In [75]:
ndarray[-2]

3

In [77]:
ndarray[:-2]

array([1, 2])

In [3]:
import numpy as np

In [31]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [5]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
ndarray.shape

(4, 4)

In [10]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [32]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

### np.arange(),np.linspace(),np.logspace()

In [16]:
np.arange(2, 15, 2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [17]:
list(range(2, 15,2))

[2, 4, 6, 8, 10, 12, 14]

In [30]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [4]:
np.linspace(0, 3, 10, endpoint=True)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [32]:
np.logspace(0, 3, 10, endpoint=False)

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

### 行列生成(zeros,ones,eye)

#### np.zeros(shape)

In [34]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.zeros((3, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

#### np.ones(shape)

In [41]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.zeros((2, 3)) + 8

array([[8., 8., 8.],
       [8., 8., 8.]])

In [45]:
np.ones((2, 3))*4

array([[4., 4., 4.],
       [4., 4., 4.]])

#### np.eye()

In [46]:
# I identify matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### np.randomを使って乱数生成

In [1]:
import numpy as np

### np.random.rand()

In [5]:
## 疑似乱数　pseudo random
np.random.rand()

0.13347080852825843

In [4]:
np.random.rand(3, 4)

array([[0.61675816, 0.80489032, 0.97993364, 0.38505177],
       [0.52561697, 0.66238364, 0.95841815, 0.18724328],
       [0.0514778 , 0.46951367, 0.56104585, 0.56182144]])

In [7]:
np.random.seed(1)
np.random.rand()

0.417022004702574

### np.random.randn()

In [12]:
np.random.randn(2, 3)

array([[-0.4531686 ,  0.60415364,  2.38520581],
       [-0.12388333, -0.32419367,  0.31075423]])

In [19]:
# 平均３　分散４のランダム
np.random.normal(3, 4, (2, 3))

array([[ 2.27631879,  0.58431749, -1.92023254],
       [ 5.20214998,  6.17122746,  0.50587708]])

In [18]:
# １０以上１００未満の２✕３
np.random.randint(10, 100, (2, 3))

array([[74, 70, 88],
       [27, 49, 45]])

### np.random.choice()

In [20]:
a = [1, 2, 3]
np.random.choice(a)

3

In [37]:
index_pool = np.arange(0, 5, 1)
index_pool

array([0, 1, 2, 3, 4])

In [38]:
idx = np.random.choice(index_pool)

In [43]:
idx

1

In [40]:
ndarray.shape

(4, 4)

In [44]:
ndarray[idx, idx]

6

In [46]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 統計量を求める

In [4]:
std_norm = np.random.randn(5, 5)
std_norm

array([[-0.57451586, -1.46298765,  1.10717492, -1.91987252, -1.83148462],
       [-1.15266193, -0.28654941, -1.3847975 , -0.87743952,  0.35456523],
       [-0.62581313,  0.66709619,  0.25987842, -0.13456289,  0.41748256],
       [-0.49331327, -1.18898941, -0.66573192,  0.59999045,  0.24026616],
       [ 0.473182  ,  0.48059146,  0.26985561, -0.65003279,  1.06250979]])

In [48]:
#　最大値
std_norm.max()

1.7786408351670806

In [51]:
np.max(std_norm)

1.7786408351670806

In [52]:
# 最小値
std_norm.min()

-1.5942187308968674

In [53]:
np.min(std_norm)

-1.5942187308968674

In [54]:
# 最大値のindexの取得
std_norm.argmax()

7

In [56]:
std_norm.flatten()[std_norm.argmax()]

1.7786408351670806

In [57]:
# 最小値のindexを取得
std_norm.argmin()

17

In [59]:
std_norm.flatten()[std_norm.argmin()]

-1.5942187308968674

In [2]:
import numpy as np

In [7]:
# 平均値を求める
std_norm.mean()

-0.003496869389280474

In [9]:
# 中央値を取得　中央値はndarrayから直接取得できない
np.median(std_norm)

0.12272473637943862

In [2]:
#　中央値vs平均値
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median took {} sec'.format(after_median - before))
print('mean took {} sec'.format(after_mean - after_median))

median took 0.15757536888122559 sec
mean took 0.002973794937133789 sec


In [12]:
np.mean(a)

0.00011193684737093363

In [1]:
import numpy as np

In [7]:
std_norm

array([[-0.57451586, -1.46298765,  1.10717492, -1.91987252, -1.83148462],
       [-1.15266193, -0.28654941, -1.3847975 , -0.87743952,  0.35456523],
       [-0.62581313,  0.66709619,  0.25987842, -0.13456289,  0.41748256],
       [-0.49331327, -1.18898941, -0.66573192,  0.59999045,  0.24026616],
       [ 0.473182  ,  0.48059146,  0.26985561, -0.65003279,  1.06250979]])

In [5]:
# 行、列ごとの統計量
std_norm.max(axis=0)  # axis=0 は列

array([0.473182  , 0.66709619, 1.10717492, 0.59999045, 1.06250979])

In [6]:
std_norm.max(axis=1)  # axis=1 は行

array([1.10717492, 0.35456523, 0.66709619, 0.59999045, 1.06250979])

## 数学で使う便利関数

In [10]:
#　平方根　square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [4]:
# Log(Logarithm)
x = np.linspace(1, 10, 10)
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [14]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
# 指数関数　Exponential function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [17]:
# ネイピア数
np.e

2.718281828459045

In [1]:
import numpy as np

In [7]:
# 合計　
array = np.arange(1, 11)
np.sum([1, 2, 3])

6

In [8]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.sum(array)

55

In [12]:
ndarray = array.reshape(2, 5)

In [14]:
np.sum(ndarray, axis=0)

array([ 7,  9, 11, 13, 15])

In [15]:
np.sum(ndarray, axis=1)

array([15, 40])

In [16]:
# 絶対値
# [-10, -9, -8]
array = np.arange(-10, 0)

In [17]:
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [18]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nanとnp.jsnan()

In [20]:
# NaN : Not a Number
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


nan

In [21]:
np.nan

nan

In [22]:
type(np.nan)

float

In [23]:
a = None
a is None

True

In [24]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

## その他便利関数

### np.clip()

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [28]:
1e-4

0.0001

In [29]:
1e100

1e+100

In [32]:
1e-1

0.1

## numpy array の condition

In [33]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
### np.where
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [35]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [36]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [3]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [9]:
result, = np.where(array > 3)

In [10]:
result

array([4, 5, 6, 7, 8, 9])

In [11]:
ndarray = array.reshape(2, 5)

In [12]:
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
ndarray[ndarray > 3]

array([4, 5, 6, 7, 8, 9])

In [14]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [16]:
# すべてTrue?
(ndarray > 3).all()

False

In [17]:
# ひとつでもTrue？
(ndarray > 3).any()

True

In [19]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [20]:
(ndarray > 3).all(axis=1)

array([False,  True])

### np.uniqu()

In [28]:
array = np.array([1, 2, 1, 1, 3, 3, 3, 3, 4, 4, 5, 7, 7, 7])

In [22]:
array

array([1, 2, 1, 1, 3, 3, 3, 3, 4, 4, 5])

In [24]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [29]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5, 7]), array([3, 1, 4, 2, 1, 3]))

### np.bincount()

In [30]:
np.bincount(array)

array([0, 3, 1, 4, 2, 1, 0, 3])

### np.concatenate()とnp.stack()

In [32]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [35]:
ndarray_odd = np.arange(1, 18, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [37]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [39]:
# 既定値は axis=0
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [44]:
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [69]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [62]:
stacked_array = _

In [63]:
stacked_array.shape

(3, 3, 2)

### np.transpose.T

In [71]:
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.15240894, -2.21850143, -1.02638496, -0.38558946],
       [ 1.07001752,  0.41327162, -0.83175778, -1.60541449],
       [-0.77260053,  1.33574416, -1.44543918, -0.57363279]])

In [72]:
ndarray.shape

(3, 4)

In [74]:
np.transpose(ndarray)

array([[ 0.15240894,  1.07001752, -0.77260053],
       [-2.21850143,  0.41327162,  1.33574416],
       [-1.02638496, -0.83175778, -1.44543918],
       [-0.38558946, -1.60541449, -0.57363279]])

In [75]:
np.transpose(ndarray).shape

(4, 3)

In [76]:
ndarray.T

array([[ 0.15240894,  1.07001752, -0.77260053],
       [-2.21850143,  0.41327162,  1.33574416],
       [-1.02638496, -0.83175778, -1.44543918],
       [-0.38558946, -1.60541449, -0.57363279]])

In [77]:
ndarray = np.random.randn(3, 4, 5)

In [78]:
ndarray

array([[[-1.86561706e+00, -6.82822811e-01, -6.86703139e-01,
         -4.91699416e-01,  9.79772267e-02],
        [-2.68501607e-01, -2.07056962e+00, -5.89467065e-01,
          1.17455001e+00, -6.38838173e-01],
        [-6.58571246e-01, -7.50932739e-03, -7.04876128e-01,
          7.61247725e-01,  1.16571403e+00],
        [-9.79918516e-01, -9.99074225e-02, -2.33887873e+00,
          1.09905558e+00, -2.40438179e+00]],

       [[ 1.10010405e+00,  6.08842419e-01,  2.18458450e-02,
         -1.04295909e+00, -2.39701129e-03],
        [ 6.19035065e-01, -2.82325134e-03,  1.54836648e-02,
         -1.20694973e+00,  1.99014542e+00],
        [-2.50240224e+00, -1.04318374e+00, -1.05663952e-01,
          7.10924812e-02,  2.04127913e-01],
        [ 9.79011831e-01, -4.82795451e-01, -1.10223225e+00,
         -5.49393037e-01, -1.49429685e+00]],

       [[ 1.07344141e+00, -4.19979120e-01,  1.89233092e+00,
         -2.01827568e+00,  4.92192362e-01],
        [-1.55527598e+00, -1.49135837e+00,  9.58984597e-01,


In [79]:
ndarray.shape

(3, 4, 5)

In [80]:
ndarray.T

array([[[-1.86561706e+00,  1.10010405e+00,  1.07344141e+00],
        [-2.68501607e-01,  6.19035065e-01, -1.55527598e+00],
        [-6.58571246e-01, -2.50240224e+00,  1.12110062e+00],
        [-9.79918516e-01,  9.79011831e-01,  4.86953989e-04]],

       [[-6.82822811e-01,  6.08842419e-01, -4.19979120e-01],
        [-2.07056962e+00, -2.82325134e-03, -1.49135837e+00],
        [-7.50932739e-03, -1.04318374e+00,  4.16666279e-01],
        [-9.99074225e-02, -4.82795451e-01,  8.16432440e-01]],

       [[-6.86703139e-01,  2.18458450e-02,  1.89233092e+00],
        [-5.89467065e-01,  1.54836648e-02,  9.58984597e-01],
        [-7.04876128e-01, -1.05663952e-01,  6.71064257e-01],
        [-2.33887873e+00, -1.10223225e+00,  1.11400490e+00]],

       [[-4.91699416e-01, -1.04295909e+00, -2.01827568e+00],
        [ 1.17455001e+00, -1.20694973e+00,  2.53673339e+00],
        [ 7.61247725e-01,  7.10924812e-02, -2.65315274e+00],
        [ 1.09905558e+00, -5.49393037e-01,  1.61210304e-01]],

       [[ 9.7977

In [82]:
ndarray.T.shape

(5, 4, 3)

### np.save('path',array)とnp.load('path')

In [1]:
import numpy as np

In [4]:
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [5]:
np.save('sample_ndarray.npy', ndarray)

In [30]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [10]:
dictionary = {
    'id': 12345,
    'image': 
}

In [12]:
np.save('dictionary', dictionary)

In [16]:
loaded_dict = np.load('dictionary.npy', allow_pickle=True)　# このままだとarrayとしてloadされてしまう

In [18]:
loaded_dict = np.load('dictionary.npy', allow_pickle=True)[()]  # [()]を付ける

In [28]:
loaded_dict['image']

array([[[ 1.46785194, -0.33876146, -0.22904209, -1.40595167,
         -0.95220624],
        [ 0.17855145, -0.88056633, -1.35225509,  1.69200708,
         -0.51435355],
        [-0.02011837, -0.78668624, -1.07236029, -0.96429121,
          0.35632794],
        [ 0.0342879 ,  0.98974135, -0.6814176 , -0.73626126,
         -1.32196797]],

       [[-0.62482468, -0.30026483,  1.10589457,  0.79120361,
          0.39331771],
        [-0.69459501,  1.15646056, -0.46247649,  0.71532243,
          1.49869674],
        [ 0.07321712,  0.93611255,  1.04963805, -1.59915321,
         -0.62330704],
        [-0.35816398, -0.57299947,  0.86449888,  0.69416265,
          0.21715917]],

       [[-2.17941306, -0.40380471,  0.70107603, -0.2512239 ,
          1.50200791],
        [ 2.05521956,  0.4001604 , -0.56568889, -0.78406726,
          0.22397425],
        [ 0.23089947, -0.45481217,  0.57310807,  0.51768379,
          0.51423722],
        [-0.03682534, -0.22525168, -1.16394788,  0.22924839,
         -0